!io
version: 0
type: xml
param_root: !list
  objects:
    DemoAIActionIdx: !obj
      Demo_ApplyEnvSet: 1
      Demo_Join: 2
      Demo_PlayASForDemo: 3
      Demo_PlayASForTimeline: 4
      Demo_ResetBoneCtrl: 5
      Demo_SendSignal: 6
      Demo_SetBloodyMoonEnv: 7
      Demo_SetGetFlag: 8
      Demo_SetLensFlare: 9
      Demo_TrigNullASPlay: 10
      Demo_VisibleOff: 11
      Demo_XLinkEventCreate: 12
      Demo_XLinkEventFade: 13
      Demo_XLinkEventKill: 14
  lists:
    AI: !list
      objects: {}
      lists: {}
    Action: !list
      objects: {}
      lists:
        Action_0: !list
          objects:
            Def: !obj {Name: Root, ClassName: !str32 DummyAction, GroupName: ''}
          lists: {}
        Action_1: !list
          objects:
            Def: !obj {Name: Demo_ApplyEnvSet, ClassName: !str32 SystemApplyEnvSetAction,
              GroupName: ''}
          lists: {}
        Action_2: !list
          objects:
            Def: !obj {Name: Demo_Join, ClassName: !str32 DummyTriggerAction, GroupName: ''}
          lists: {}
        Action_3: !list
          objects:
            Def: !obj {Name: Demo_PlayASForDemo, ClassName: !str32 PlayASForDemo,
              GroupName: ''}
            SInst: !obj {AnimeDrivenSettings: 1}
          lists: {}
        Action_4: !list
          objects:
            Def: !obj {Name: Demo_PlayASForTimeline, ClassName: !str32 PlayASForTimeline,
              GroupName: ''}
            SInst: !obj {AnimeDrivenSettings: 1}
          lists: {}
        Action_5: !list
          objects:
            Def: !obj {Name: Demo_ResetBoneCtrl, ClassName: !str32 DemoResetBoneCtrl,
              GroupName: ''}
          lists: {}
        Action_6: !list
          objects:
            Def: !obj {Name: Demo_SendSignal, ClassName: !str32 SendSignalAction,
              GroupName: ''}
          lists: {}
        Action_7: !list
          objects:
            Def: !obj {Name: Demo_SetBloodyMoonEnv, ClassName: !str32 SetBloodyMoonEnv,
              GroupName: ''}
          lists: {}
        Action_8: !list
          objects:
            Def: !obj {Name: Demo_SetGetFlag, ClassName: !str32 SetGetFlag, GroupName: ''}
          lists: {}
        Action_9: !list
          objects:
            Def: !obj {Name: Demo_SetLensFlare, ClassName: !str32 EnvSetLensFlare,
              GroupName: ''}
          lists: {}
        Action_10: !list
          objects:
            Def: !obj {Name: Demo_TrigNullASPlay, ClassName: !str32 EventTrigNullASPlay,
              GroupName: ''}
          lists: {}
        Action_11: !list
          objects:
            Def: !obj {Name: Demo_VisibleOff, ClassName: !str32 DemoVisibleOff, GroupName: ''}
          lists: {}
        Action_12: !list
          objects:
            Def: !obj {Name: Demo_XLinkEventCreate, ClassName: !str32 XLinkEventCreateAction,
              GroupName: ''}
          lists: {}
        Action_13: !list
          objects:
            Def: !obj {Name: Demo_XLinkEventFade, ClassName: !str32 XLinkEventFadeAction,
              GroupName: ''}
          lists: {}
        Action_14: !list
          objects:
            Def: !obj {Name: Demo_XLinkEventKill, ClassName: !str32 XLinkEventKillAction,
              GroupName: ''}
          lists: {}
    Behavior: !list
      objects: {}
      lists: {}
    Query: !list
      objects: {}
      lists: {}
